"""Remove ENUMS for simplicity

Revision ID: 7897919c41fc
Revises: 66b67080f995
Create Date: 2024-12-21 14:40:48.154047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7897919c41fc'
down_revision = '66b67080f995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=postgresql.ENUM('FRESHMAN', 'SOPHOMORE', 'JUNIOR', 'SENIOR', 'GRADUATE', name='yearenum'),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('FRESHMAN', 'SOPHOMORE', 'JUNIOR', 'SENIOR', 'GRADUATE', name='yearenum'),
               existing_nullable=True)

    # ### end Alembic commands ###
