"""Add GroupJoinRequest table

Revision ID: af02fbd32ff4
Revises: 178e842fc064
Create Date: 2024-12-09 21:36:17.005153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af02fbd32ff4'
down_revision = '178e842fc064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='pending', nullable=False, comment='Status of the request: pending, approved, rejected'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when the request was creted'),
    sa.ForeignKeyConstraint(['group_id'], ['study_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership_requests')
    # ### end Alembic commands ###
