"""Add membership_requests relationship

Revision ID: f5e5bd79f0b1
Revises: 0c2905c0506b
Create Date: 2024-12-16 04:24:59.840282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e5bd79f0b1'
down_revision = '0c2905c0506b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
